name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Readme
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_DAYS_OF_WEEK: bool('true')
          SHOW_OS: bool('false')
          SHOW_PROJECTS: bool('false')
          SHOW_PROFILE_VIEWS: bool('false')
          SHOW_COMMIT: bool('false')
          SHOW_LANGUAGE:  bool('true')
          SHOW_TIMEZONE: bool('false')
          SHOW_EDITORS: bool('false')
          SHOW_LANGUAGE_PER_REPO: bool('false')
          SHOW_SHORT_INFO: bool('false')
          SHOW_LOC_CHART: bool('false')
          SYMBOL_VERSION: bool('false')
