name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Readme
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_DAYS_OF_WEEK: 1
          SHOW_OS: 0
          SHOW_PROJECTS: 0
          SHOW_PROFILE_VIEWS: 0
          SHOW_COMMIT: 0
          SHOW_LANGUAGE:  1
          SHOW_TIMEZONE: 0
          SHOW_EDITORS: 0
          SHOW_LANGUAGE_PER_REPO: 0
          SHOW_SHORT_INFO: 0
          SHOW_LOC_CHART: 0
          SYMBOL_VERSION: 0
